--------------------------------------------------------
--  파일이 생성됨 - 금요일-7월-08-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_CATEGORY_NO
--------------------------------------------------------

   CREATE SEQUENCE  "JBLOG"."SEQ_CATEGORY_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 6 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_COMMENTS_NO
--------------------------------------------------------

   CREATE SEQUENCE  "JBLOG"."SEQ_COMMENTS_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 13 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_POST_NO
--------------------------------------------------------

   CREATE SEQUENCE  "JBLOG"."SEQ_POST_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 18 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_USERS_NO
--------------------------------------------------------

   CREATE SEQUENCE  "JBLOG"."SEQ_USERS_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 6 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table BLOG
--------------------------------------------------------

  CREATE TABLE "JBLOG"."BLOG" 
   (	"ID" VARCHAR2(50 BYTE), 
	"BLOG_TITLE" VARCHAR2(50 BYTE), 
	"LOGO_FILE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CATEGORY
--------------------------------------------------------

  CREATE TABLE "JBLOG"."CATEGORY" 
   (	"CATE_NO" NUMBER, 
	"ID" VARCHAR2(50 BYTE), 
	"CATE_NAME" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(500 BYTE), 
	"REG_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMMENTS
--------------------------------------------------------

  CREATE TABLE "JBLOG"."COMMENTS" 
   (	"CMT_NO" NUMBER, 
	"POST_NO" NUMBER, 
	"USER_NO" NUMBER, 
	"CMT_CONTENT" VARCHAR2(1000 BYTE), 
	"REG_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table POST
--------------------------------------------------------

  CREATE TABLE "JBLOG"."POST" 
   (	"POST_NO" NUMBER, 
	"CATE_NO" NUMBER, 
	"POST_TITLE" VARCHAR2(300 BYTE), 
	"POST_CONTENT" VARCHAR2(4000 BYTE), 
	"REG_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "JBLOG"."USERS" 
   (	"USER_NO" NUMBER, 
	"ID" VARCHAR2(50 BYTE), 
	"USER_NAME" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(50 BYTE), 
	"JOIN_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into JBLOG.BLOG
SET DEFINE OFF;
Insert into JBLOG.BLOG (ID,BLOG_TITLE,LOGO_FILE) values ('asd','28_홀수_이준규','16571709816753fb7a3e4-2a32-43b5-963a-e165115a671d.png');
Insert into JBLOG.BLOG (ID,BLOG_TITLE,LOGO_FILE) values ('asd123','이준규의 블로그입니다.',null);
REM INSERTING into JBLOG.CATEGORY
SET DEFINE OFF;
Insert into JBLOG.CATEGORY (CATE_NO,ID,CATE_NAME,DESCRIPTION,REG_DATE) values (2,'asd','213123','123123',to_date('22/07/06','RR/MM/DD'));
Insert into JBLOG.CATEGORY (CATE_NO,ID,CATE_NAME,DESCRIPTION,REG_DATE) values (3,'asd','haha','zz',to_date('22/07/06','RR/MM/DD'));
Insert into JBLOG.CATEGORY (CATE_NO,ID,CATE_NAME,DESCRIPTION,REG_DATE) values (1,'asd','dsfsdf','dsfsdf',to_date('22/07/06','RR/MM/DD'));
Insert into JBLOG.CATEGORY (CATE_NO,ID,CATE_NAME,DESCRIPTION,REG_DATE) values (4,'asd','345435','345',to_date('22/07/06','RR/MM/DD'));
Insert into JBLOG.CATEGORY (CATE_NO,ID,CATE_NAME,DESCRIPTION,REG_DATE) values (5,'asd','213','zzzz',to_date('22/07/06','RR/MM/DD'));
REM INSERTING into JBLOG.COMMENTS
SET DEFINE OFF;
Insert into JBLOG.COMMENTS (CMT_NO,POST_NO,USER_NO,CMT_CONTENT,REG_DATE) values (9,5,4,'코멘트내용',to_date('22/07/08','RR/MM/DD'));
Insert into JBLOG.COMMENTS (CMT_NO,POST_NO,USER_NO,CMT_CONTENT,REG_DATE) values (11,5,5,'gd',to_date('22/07/08','RR/MM/DD'));
Insert into JBLOG.COMMENTS (CMT_NO,POST_NO,USER_NO,CMT_CONTENT,REG_DATE) values (12,5,5,'ㅎㅇㅎㅇ',to_date('22/07/08','RR/MM/DD'));
REM INSERTING into JBLOG.POST
SET DEFINE OFF;
Insert into JBLOG.POST (POST_NO,CATE_NO,POST_TITLE,POST_CONTENT,REG_DATE) values (3,1,'213','122112',to_date('22/07/07','RR/MM/DD'));
Insert into JBLOG.POST (POST_NO,CATE_NO,POST_TITLE,POST_CONTENT,REG_DATE) values (4,2,'zzzzzzzz','zzzzzzzzzzzzz',to_date('22/07/07','RR/MM/DD'));
Insert into JBLOG.POST (POST_NO,CATE_NO,POST_TITLE,POST_CONTENT,REG_DATE) values (5,5,'제발 되라','제발 되주세요',to_date('22/07/07','RR/MM/DD'));
Insert into JBLOG.POST (POST_NO,CATE_NO,POST_TITLE,POST_CONTENT,REG_DATE) values (6,4,'ㅇㄹㅇㄴ','ㅇㄴㄹ',to_date('22/07/07','RR/MM/DD'));
Insert into JBLOG.POST (POST_NO,CATE_NO,POST_TITLE,POST_CONTENT,REG_DATE) values (7,3,'ㄴㅇㄹ','ㄴㅇㄹㄴㅇㄹ',to_date('22/07/07','RR/MM/DD'));
Insert into JBLOG.POST (POST_NO,CATE_NO,POST_TITLE,POST_CONTENT,REG_DATE) values (8,5,'dfgdfg','fddfgfdg',to_date('22/07/08','RR/MM/DD'));
Insert into JBLOG.POST (POST_NO,CATE_NO,POST_TITLE,POST_CONTENT,REG_DATE) values (9,5,'1','1',to_date('22/07/08','RR/MM/DD'));
Insert into JBLOG.POST (POST_NO,CATE_NO,POST_TITLE,POST_CONTENT,REG_DATE) values (10,5,'2','2',to_date('22/07/08','RR/MM/DD'));
Insert into JBLOG.POST (POST_NO,CATE_NO,POST_TITLE,POST_CONTENT,REG_DATE) values (11,5,'3','3',to_date('22/07/08','RR/MM/DD'));
Insert into JBLOG.POST (POST_NO,CATE_NO,POST_TITLE,POST_CONTENT,REG_DATE) values (12,5,'4','4',to_date('22/07/08','RR/MM/DD'));
Insert into JBLOG.POST (POST_NO,CATE_NO,POST_TITLE,POST_CONTENT,REG_DATE) values (1,1,'1231','213',to_date('22/07/07','RR/MM/DD'));
Insert into JBLOG.POST (POST_NO,CATE_NO,POST_TITLE,POST_CONTENT,REG_DATE) values (2,1,'ㅁㄴㅇㅁㄴㅇ','ㅁㄴㅇㅁㄴㅇㅁㄴㅇ',to_date('22/07/07','RR/MM/DD'));
Insert into JBLOG.POST (POST_NO,CATE_NO,POST_TITLE,POST_CONTENT,REG_DATE) values (13,5,'5','5',to_date('22/07/08','RR/MM/DD'));
Insert into JBLOG.POST (POST_NO,CATE_NO,POST_TITLE,POST_CONTENT,REG_DATE) values (14,5,'6','6',to_date('22/07/08','RR/MM/DD'));
Insert into JBLOG.POST (POST_NO,CATE_NO,POST_TITLE,POST_CONTENT,REG_DATE) values (15,5,'7','7',to_date('22/07/08','RR/MM/DD'));
Insert into JBLOG.POST (POST_NO,CATE_NO,POST_TITLE,POST_CONTENT,REG_DATE) values (16,5,'8','8',to_date('22/07/08','RR/MM/DD'));
Insert into JBLOG.POST (POST_NO,CATE_NO,POST_TITLE,POST_CONTENT,REG_DATE) values (17,5,'9','9',to_date('22/07/08','RR/MM/DD'));
REM INSERTING into JBLOG.USERS
SET DEFINE OFF;
Insert into JBLOG.USERS (USER_NO,ID,USER_NAME,PASSWORD,JOIN_DATE) values (4,'asd','zz','zz',to_date('22/07/06','RR/MM/DD'));
Insert into JBLOG.USERS (USER_NO,ID,USER_NAME,PASSWORD,JOIN_DATE) values (5,'asd123','이준규','zz',to_date('22/07/07','RR/MM/DD'));
--------------------------------------------------------
--  Constraints for Table COMMENTS
--------------------------------------------------------

  ALTER TABLE "JBLOG"."COMMENTS" ADD PRIMARY KEY ("CMT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JBLOG"."COMMENTS" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "JBLOG"."COMMENTS" MODIFY ("CMT_CONTENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CATEGORY
--------------------------------------------------------

  ALTER TABLE "JBLOG"."CATEGORY" ADD PRIMARY KEY ("CATE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JBLOG"."CATEGORY" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "JBLOG"."CATEGORY" MODIFY ("CATE_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POST
--------------------------------------------------------

  ALTER TABLE "JBLOG"."POST" ADD PRIMARY KEY ("POST_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JBLOG"."POST" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "JBLOG"."POST" MODIFY ("POST_TITLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "JBLOG"."USERS" ADD UNIQUE ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JBLOG"."USERS" ADD PRIMARY KEY ("USER_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JBLOG"."USERS" MODIFY ("JOIN_DATE" NOT NULL ENABLE);
  ALTER TABLE "JBLOG"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "JBLOG"."USERS" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "JBLOG"."USERS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BLOG
--------------------------------------------------------

  ALTER TABLE "JBLOG"."BLOG" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JBLOG"."BLOG" MODIFY ("BLOG_TITLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BLOG
--------------------------------------------------------

  ALTER TABLE "JBLOG"."BLOG" ADD CONSTRAINT "BLOG_FK" FOREIGN KEY ("ID")
	  REFERENCES "JBLOG"."USERS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CATEGORY
--------------------------------------------------------

  ALTER TABLE "JBLOG"."CATEGORY" ADD CONSTRAINT "CATEGORY_FK" FOREIGN KEY ("ID")
	  REFERENCES "JBLOG"."BLOG" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMENTS
--------------------------------------------------------

  ALTER TABLE "JBLOG"."COMMENTS" ADD CONSTRAINT "COMMENTS_FK1" FOREIGN KEY ("POST_NO")
	  REFERENCES "JBLOG"."POST" ("POST_NO") ENABLE;
  ALTER TABLE "JBLOG"."COMMENTS" ADD CONSTRAINT "COMMENTS_FK2" FOREIGN KEY ("USER_NO")
	  REFERENCES "JBLOG"."USERS" ("USER_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POST
--------------------------------------------------------

  ALTER TABLE "JBLOG"."POST" ADD CONSTRAINT "POST_FK" FOREIGN KEY ("CATE_NO")
	  REFERENCES "JBLOG"."CATEGORY" ("CATE_NO") ENABLE;
